# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DoubleClick <- function(x, y) {
    invisible(.Call(`_clickpaste_DoubleClick`, x, y))
}

get_point_x <- function() {
    .Call(`_clickpaste_get_point_x`)
}

get_point_y <- function() {
    .Call(`_clickpaste_get_point_y`)
}

shift <- function() {
    .Call(`_clickpaste_shift`)
}

a_1 <- function() {
    .Call(`_clickpaste_a_1`)
}

b_1 <- function() {
    .Call(`_clickpaste_b_1`)
}

c_1 <- function() {
    .Call(`_clickpaste_c_1`)
}

d_1 <- function() {
    .Call(`_clickpaste_d_1`)
}

e_1 <- function() {
    .Call(`_clickpaste_e_1`)
}

f_1 <- function() {
    .Call(`_clickpaste_f_1`)
}

g_1 <- function() {
    .Call(`_clickpaste_g_1`)
}

h_1 <- function() {
    .Call(`_clickpaste_h_1`)
}

i_1 <- function() {
    .Call(`_clickpaste_i_1`)
}

j_1 <- function() {
    .Call(`_clickpaste_j_1`)
}

k_1 <- function() {
    .Call(`_clickpaste_k_1`)
}

l_1 <- function() {
    .Call(`_clickpaste_l_1`)
}

m_1 <- function() {
    .Call(`_clickpaste_m_1`)
}

n_1 <- function() {
    .Call(`_clickpaste_n_1`)
}

o_1 <- function() {
    .Call(`_clickpaste_o_1`)
}

p_1 <- function() {
    .Call(`_clickpaste_p_1`)
}

q_1 <- function() {
    .Call(`_clickpaste_q_1`)
}

r_1 <- function() {
    .Call(`_clickpaste_r_1`)
}

s_1 <- function() {
    .Call(`_clickpaste_s_1`)
}

t_1 <- function() {
    .Call(`_clickpaste_t_1`)
}

u_1 <- function() {
    .Call(`_clickpaste_u_1`)
}

v_1 <- function() {
    .Call(`_clickpaste_v_1`)
}

w_1 <- function() {
    .Call(`_clickpaste_w_1`)
}

x_1 <- function() {
    .Call(`_clickpaste_x_1`)
}

y_1 <- function() {
    .Call(`_clickpaste_y_1`)
}

z_1 <- function() {
    .Call(`_clickpaste_z_1`)
}

zero_1 <- function() {
    .Call(`_clickpaste_zero_1`)
}

one_1 <- function() {
    .Call(`_clickpaste_one_1`)
}

two_1 <- function() {
    .Call(`_clickpaste_two_1`)
}

three_1 <- function() {
    .Call(`_clickpaste_three_1`)
}

four_1 <- function() {
    .Call(`_clickpaste_four_1`)
}

five_1 <- function() {
    .Call(`_clickpaste_five_1`)
}

six_1 <- function() {
    .Call(`_clickpaste_six_1`)
}

seven_1 <- function() {
    .Call(`_clickpaste_seven_1`)
}

eight_1 <- function() {
    .Call(`_clickpaste_eight_1`)
}

nine_1 <- function() {
    .Call(`_clickpaste_nine_1`)
}

funtion_1 <- function() {
    .Call(`_clickpaste_funtion_1`)
}

funtion_2 <- function() {
    .Call(`_clickpaste_funtion_2`)
}

funtion_3 <- function() {
    .Call(`_clickpaste_funtion_3`)
}

funtion_4 <- function() {
    .Call(`_clickpaste_funtion_4`)
}

funtion_5 <- function() {
    .Call(`_clickpaste_funtion_5`)
}

funtion_6 <- function() {
    .Call(`_clickpaste_funtion_6`)
}

funtion_7 <- function() {
    .Call(`_clickpaste_funtion_7`)
}

funtion_8 <- function() {
    .Call(`_clickpaste_funtion_8`)
}

funtion_9 <- function() {
    .Call(`_clickpaste_funtion_9`)
}

funtion_10 <- function() {
    .Call(`_clickpaste_funtion_10`)
}

funtion_11 <- function() {
    .Call(`_clickpaste_funtion_11`)
}

funtion_12 <- function() {
    .Call(`_clickpaste_funtion_12`)
}

enter_1 <- function() {
    .Call(`_clickpaste_enter_1`)
}

backspace_1 <- function() {
    .Call(`_clickpaste_backspace_1`)
}

delete_1 <- function() {
    .Call(`_clickpaste_delete_1`)
}

control_a <- function() {
    .Call(`_clickpaste_control_a`)
}

alter_1 <- function() {
    .Call(`_clickpaste_alter_1`)
}

pageup_1 <- function() {
    .Call(`_clickpaste_pageup_1`)
}

pagedown_1 <- function() {
    .Call(`_clickpaste_pagedown_1`)
}

escape_1 <- function() {
    .Call(`_clickpaste_escape_1`)
}

paste_1 <- function() {
    .Call(`_clickpaste_paste_1`)
}

RightClick <- function(x, y) {
    invisible(.Call(`_clickpaste_RightClick`, x, y))
}

SingleClick <- function(x, y) {
    invisible(.Call(`_clickpaste_SingleClick`, x, y))
}

